<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DosenSeeder1 extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('mst_dosen')->insertOrIgnore([
            [
                'id' => 13,
                'prodi_id' => 7,
                'kode' => '80177',
                'nidn' => '2122118101',
                'nama' => 'Kholili Hasib',
                'gelar_depan' => 'Dr.',
                'gelar_belakang' => 'M.Ud',
                'jk_id' => 8,
                'tempat_lahir' => 'KABUPATEN PASURUAN',
                'tanggal_lahir' => '1981-11-22',
                'alamat' => 'Sangeng Utara Bendomungal Bangil',
                'kota_id' => 3514,
                'email' => 'kholilihasib@uiidalwa.ac.id',
                'hp' => '085280081906',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-03 02:55:52',
                'updated_at' => '2025-01-30 06:51:35',
            ],
            [
                'id' => 14,
                'prodi_id' => 8,
                'kode' => '80172',
                'nidn' => '2115088303',
                'nama' => 'A. ROISUL BURHANI',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Pd.I',
                'jk_id' => 8,
                'tempat_lahir' => 'KABUPATEN SIDOARJO',
                'tanggal_lahir' => '1983-08-15',
                'alamat' => 'SIDOARJO',
                'kota_id' => 3514,
                'email' => 'samirrois83@gmail.com',
                'hp' => '08980432223',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-03 03:03:37',
                'updated_at' => '2025-01-30 06:51:35',
            ],
            [
                'id' => 15,
                'prodi_id' => 6,
                'kode' => '80133',
                'nidn' => '2104087201',
                'nama' => 'ABDUL KADIR',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Ag',
                'jk_id' => 8,
                'tempat_lahir' => 'KABUPATEN PASURUAN',
                'tanggal_lahir' => '1972-08-04',
                'alamat' => 'PASURUAN',
                'kota_id' => 3514,
                'email' => 'qodira72@gmail.com',
                'hp' => '081334240535',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-03 03:05:35',
                'updated_at' => '2025-01-29 08:55:35',
            ],
            [
                'id' => 16,
                'prodi_id' => 9,
                'kode' => '80173',
                'nidn' => '2129047101',
                'nama' => 'AHMAD MISBAH',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Pd.I',
                'jk_id' => 8,
                'tempat_lahir' => 'KOTA SURABAYA',
                'tanggal_lahir' => '1971-04-29',
                'alamat' => 'sidoarjo',
                'kota_id' => 3515,
                'email' => 'abfarsy@gmail.com',
                'hp' => '085335354055',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-06 03:10:07',
                'updated_at' => '2025-01-30 06:51:35',
            ],
            [
                'id' => 17,
                'prodi_id' => 3,
                'kode' => '80151',
                'nidn' => '2119048101',
                'nama' => 'AZIZ AKBAR, SHI.',
                'gelar_depan' => 'Dr.',
                'gelar_belakang' => 'M.E.I',
                'jk_id' => 8,
                'tempat_lahir' => 'KABUPATEN GRESIK',
                'tanggal_lahir' => '1981-04-19',
                'alamat' => 'PASURUAN',
                'kota_id' => 3514,
                'email' => 'aziz.akbar1981@gmail.com',
                'hp' => '082232008610',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-06 03:13:02',
                'updated_at' => '2025-08-20 09:34:58',
            ],
            [
                'id' => 18,
                'prodi_id' => 7,
                'kode' => '80170',
                'nidn' => '2112037301',
                'nama' => 'Dr. BAHRU ROZI',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Pd.I',
                'jk_id' => 8,
                'tempat_lahir' => 'KABUPATEN PASURUAN',
                'tanggal_lahir' => '1973-03-12',
                'alamat' => 'MARGOREJO 1-G/8 SURABAYA',
                'kota_id' => 3578,
                'email' => 'rozibahru45@gmail.com',
                'hp' => '081935045412',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-06 03:24:58',
                'updated_at' => '2025-12-24 14:31:40',
            ],
            [
                'id' => 19,
                'prodi_id' => 3,
                'kode' => '80149',
                'nidn' => '2109018901',
                'nama' => 'INAYATUL MAULA',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Pd',
                'jk_id' => 9,
                'tempat_lahir' => 'KABUPATEN PASURUAN',
                'tanggal_lahir' => '1989-01-09',
                'alamat' => 'PASURUAN',
                'kota_id' => 3514,
                'email' => 'iinplakat@gmail.com',
                'hp' => '085298958963',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-06 03:27:22',
                'updated_at' => '2025-01-29 08:55:35',
            ],
            [
                'id' => 20,
                'prodi_id' => 3,
                'kode' => '80233',
                'nidn' => '2122089202',
                'nama' => 'KHOIRUN NISA',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.SEI.',
                'jk_id' => 9,
                'tempat_lahir' => 'KABUPATEN TRENGGALEK',
                'tanggal_lahir' => '1992-08-22',
                'alamat' => 'Trenggalek',
                'kota_id' => 3503,
                'email' => 'manjaddawajada09@gmail.com',
                'hp' => '082143630923',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 470,
                'user_id' => 8,
                'created_at' => '2021-01-06 03:32:07',
                'updated_at' => '2025-01-30 06:51:35',
            ],
            [
                'id' => 21,
                'prodi_id' => 3,
                'kode' => '80226',
                'nidn' => '2120048003',
                'nama' => "M ROBI'IN",
                'gelar_depan' => null,
                'gelar_belakang' => ',M.M.',
                'jk_id' => 8,
                'tempat_lahir' => 'KABUPATEN MOJOKERTO',
                'tanggal_lahir' => '1980-04-20',
                'alamat' => 'MOJOKERTO',
                'kota_id' => 3516,
                'email' => 'robiinahmad@gmail.com',
                'hp' => '081357241309',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-06 03:40:14',
                'updated_at' => '2025-05-24 15:46:54',
            ],
            [
                'id' => 22,
                'prodi_id' => 7,
                'kode' => '80189',
                'nidn' => '2111048301',
                'nama' => 'M. AKHSANUDIN,M.Pd.I',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Pd.I',
                'jk_id' => 8,
                'tempat_lahir' => 'KABUPATEN TEGAL',
                'tanggal_lahir' => '1983-04-11',
                'alamat' => 'TEGAL',
                'kota_id' => 3328,
                'email' => 'moch.ahsanudin@gmail.com',
                'hp' => '082210357510',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-06 03:42:44',
                'updated_at' => '2025-01-29 08:55:35',
            ],
            [
                'id' => 23,
                'prodi_id' => 3,
                'kode' => '80178',
                'nidn' => '2130058801',
                'nama' => 'WARDATUL FITRIYAH',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Th.I',
                'jk_id' => 9,
                'tempat_lahir' => 'KABUPATEN PASURUAN',
                'tanggal_lahir' => '1988-05-30',
                'alamat' => 'PASURUAN',
                'kota_id' => 3514,
                'email' => 'wardah.fitriyah@gmail.com',
                'hp' => '085336503655',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-06 03:57:05',
                'updated_at' => '2025-01-29 08:55:35',
            ],
            [
                'id' => 24,
                'prodi_id' => 3,
                'kode' => '80236',
                'nidn' => '2118048403',
                'nama' => 'WELLY KUSWANTO',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Pd',
                'jk_id' => 8,
                'tempat_lahir' => 'KABUPATEN PROBOLINGGO',
                'tanggal_lahir' => '1984-04-18',
                'alamat' => 'MALANG',
                'kota_id' => 3507,
                'email' => 'wellykuswanto@gmail.com',
                'hp' => '085236279490',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-06 04:01:21',
                'updated_at' => '2025-01-29 08:55:35',
            ],
            [
                'id' => 25,
                'prodi_id' => 4,
                'kode' => '80222',
                'nidn' => '2114078702',
                'nama' => 'GALUH ANDINA PUTRI',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Psi',
                'jk_id' => 9,
                'tempat_lahir' => 'KOTA JAKARTA SELATAN',
                'tanggal_lahir' => '1987-07-14',
                'alamat' => 'MALANG',
                'kota_id' => 3573,
                'email' => 'hjhjhjh@gmail.com',
                'hp' => '081334280759',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 10771,
                'created_at' => '2021-01-06 04:07:49',
                'updated_at' => '2025-09-18 16:40:32',
            ],
            [
                'id' => 26,
                'prodi_id' => 4,
                'kode' => '80220',
                'nidn' => '2102118703',
                'nama' => 'MOHAMAD SYAFIQ',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Pd',
                'jk_id' => 8,
                'tempat_lahir' => 'KABUPATEN PASURUAN',
                'tanggal_lahir' => '1987-11-02',
                'alamat' => 'PASURUAN',
                'kota_id' => 3514,
                'email' => 'syafiq.dalwa@gmail.com',
                'hp' => '081359556120',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-06 04:11:47',
                'updated_at' => '2025-01-30 06:51:35',
            ],
            [
                'id' => 27,
                'prodi_id' => 8,
                'kode' => '80180',
                'nidn' => '2108068301',
                'nama' => 'NASRON HAKIM,M.Pd.I',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Pd.I',
                'jk_id' => 8,
                'tempat_lahir' => 'KABUPATEN MALANG',
                'tanggal_lahir' => '1983-06-08',
                'alamat' => 'PONOROGO',
                'kota_id' => 3502,
                'email' => 'nuhat.bolalang@gmail.com',
                'hp' => '085878666780',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-06 04:14:23',
                'updated_at' => '2025-01-29 08:55:35',
            ],
            [
                'id' => 28,
                'prodi_id' => 4,
                'kode' => '80186',
                'nidn' => '2117059101',
                'nama' => 'NUKE LADYNA ANGGERAWATI',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Hum',
                'jk_id' => 9,
                'tempat_lahir' => 'KOTA SURABAYA',
                'tanggal_lahir' => '1991-05-17',
                'alamat' => 'SURABAYA',
                'kota_id' => 3578,
                'email' => 'ladynanuke057@gmail.com',
                'hp' => '082143326103',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-06 04:16:22',
                'updated_at' => '2025-01-29 08:55:35',
            ],
            [
                'id' => 29,
                'prodi_id' => 4,
                'kode' => '80181',
                'nidn' => '2113107702',
                'nama' => 'NURUL MUZAKKIYAH',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Psi',
                'jk_id' => 9,
                'tempat_lahir' => 'KOTA SURABAYA',
                'tanggal_lahir' => '1977-10-13',
                'alamat' => 'SURABAYA',
                'kota_id' => 3578,
                'email' => 'nurulmuzakkiyah13101977@gmail.com',
                'hp' => '085234020594',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 10771,
                'created_at' => '2021-01-06 04:18:25',
                'updated_at' => '2025-05-26 15:50:49',
            ],
            [
                'id' => 30,
                'prodi_id' => 10,
                'kode' => '80206',
                'nidn' => '2110129001',
                'nama' => 'RIZKA ANUGRAH',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Pd.I',
                'jk_id' => 9,
                'tempat_lahir' => 'KABUPATEN GRESIK',
                'tanggal_lahir' => '1990-12-10',
                'alamat' => 'PASURUAN',
                'kota_id' => 3575,
                'email' => 'rizka.irtadhoni@gmail.com',
                'hp' => '085850960804',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-06 04:23:22',
                'updated_at' => '2025-01-29 08:55:35',
            ],
            [
                'id' => 31,
                'prodi_id' => 4,
                'kode' => '80223',
                'nidn' => '2113068704',
                'nama' => 'SAIRAH',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Psi',
                'jk_id' => 9,
                'tempat_lahir' => 'KABUPATEN PASURUAN',
                'tanggal_lahir' => '1987-06-13',
                'alamat' => 'MALANG',
                'kota_id' => 3573,
                'email' => 'kklklk@gmail.com',
                'hp' => '089787878787',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 470,
                'user_id' => 8,
                'created_at' => '2021-01-06 04:29:46',
                'updated_at' => '2025-01-23 10:50:49',
            ],
            [
                'id' => 32,
                'prodi_id' => 6,
                'kode' => '80183',
                'nidn' => '2118048905',
                'nama' => 'SAVVY DIAN FAIZZATI',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.HI',
                'jk_id' => 9,
                'tempat_lahir' => 'KABUPATEN PASURUAN',
                'tanggal_lahir' => '1989-04-18',
                'alamat' => 'Pasuruan',
                'kota_id' => 3514,
                'email' => 'sllkll@gmail.com',
                'hp' => '081334280759',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 10771,
                'created_at' => '2021-01-06 04:32:19',
                'updated_at' => '2025-06-23 17:10:50',
            ],
            [
                'id' => 33,
                'prodi_id' => 8,
                'kode' => '80211',
                'nidn' => '2120128801',
                'nama' => 'AHMAD AVISENA',
                'gelar_depan' => 'Dr.',
                'gelar_belakang' => 'M.Pd.I',
                'jk_id' => 8,
                'tempat_lahir' => 'KABUPATEN PASURUAN',
                'tanggal_lahir' => '1988-12-20',
                'alamat' => 'Pasuruan',
                'kota_id' => 3514,
                'email' => 'avisenaavant@gmail.com',
                'hp' => '082230551928',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-06 06:52:44',
                'updated_at' => '2025-01-29 09:02:15',
            ],
            [
                'id' => 34,
                'prodi_id' => 4,
                'kode' => '80216',
                'nidn' => '2122128802',
                'nama' => 'ALFAN ARIFUDDIN',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Psi',
                'jk_id' => 8,
                'tempat_lahir' => 'KOTA PASURUAN',
                'tanggal_lahir' => '1988-12-22',
                'alamat' => 'PASURUAN',
                'kota_id' => 3575,
                'email' => 'alfanarifuddin@uiidalwa.ac.id',
                'hp' => '085646384441',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-06 06:58:15',
                'updated_at' => '2025-10-08 13:33:49',
            ],
            [
                'id' => 35,
                'prodi_id' => 3,
                'kode' => '80182',
                'nidn' => '2108118903',
                'nama' => 'MOHAMMAD ROFIUDDIN',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.M',
                'jk_id' => 8,
                'tempat_lahir' => 'KABUPATEN SIDOARJO',
                'tanggal_lahir' => '1989-11-08',
                'alamat' => 'SIDOARJO',
                'kota_id' => 3515,
                'email' => 'mohammad.rofiuddin@gmail.com',
                'hp' => '081222322246',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-06 07:00:42',
                'updated_at' => '2025-01-30 06:51:35',
            ],
            [
                'id' => 36,
                'prodi_id' => 5,
                'kode' => '80179',
                'nidn' => '2113059002',
                'nama' => 'MUHAMMAD IQBAL DEWANTARA',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Pd.I',
                'jk_id' => 8,
                'tempat_lahir' => 'KOTA SURABAYA',
                'tanggal_lahir' => '1990-05-13',
                'alamat' => 'SURABAYA',
                'kota_id' => 3578,
                'email' => 'dewantara13@gmail.com',
                'hp' => '08563241335',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-07 01:46:16',
                'updated_at' => '2025-01-29 08:55:35',
            ],
            [
                'id' => 37,
                'prodi_id' => 10,
                'kode' => '80191',
                'nidn' => '2104088702',
                'nama' => 'MUHAMMAD SHOLAH ULAYYA',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Pd.I',
                'jk_id' => 8,
                'tempat_lahir' => 'KABUPATEN PATI',
                'tanggal_lahir' => '1987-08-04',
                'alamat' => 'SIDOARJO',
                'kota_id' => 3515,
                'email' => 'solahporong@gmail.com',
                'hp' => '081233945657',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 7,
                'created_at' => '2021-01-07 01:48:09',
                'updated_at' => '2025-04-20 16:55:32',
            ],
            [
                'id' => 38,
                'prodi_id' => 5,
                'kode' => '80138',
                'nidn' => '2111117901',
                'nama' => 'NOVIANTO PUJI RAHARJO',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.I.Kom',
                'jk_id' => 8,
                'tempat_lahir' => 'KOTA SURABAYA',
                'tanggal_lahir' => '1979-11-11',
                'alamat' => 'SURABAYA',
                'kota_id' => 3578,
                'email' => 'nopy.pr@gmail.com',
                'hp' => '08155059697',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-07 01:50:09',
                'updated_at' => '2025-01-29 08:55:35',
            ],
            [
                'id' => 39,
                'prodi_id' => 5,
                'kode' => '80217',
                'nidn' => '2118069002',
                'nama' => 'REIZA PRASELANOVA',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.I.Kom',
                'jk_id' => 8,
                'tempat_lahir' => 'KOTA YOGYAKARTA',
                'tanggal_lahir' => '1990-06-18',
                'alamat' => 'SURABAYA',
                'kota_id' => 3578,
                'email' => 'praselanova@gmail.com',
                'hp' => '082143200773',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-07 01:52:15',
                'updated_at' => '2025-01-29 08:55:35',
            ],
            [
                'id' => 40,
                'prodi_id' => 6,
                'kode' => '80139',
                'nidn' => '2105068403',
                'nama' => 'HAZARUL ASWAT',
                'gelar_depan' => 'Dr.',
                'gelar_belakang' => 'M.HI',
                'jk_id' => 8,
                'tempat_lahir' => 'KABUPATEN KUBU RAYA',
                'tanggal_lahir' => '1984-06-05',
                'alamat' => 'Pasuruan',
                'kota_id' => 3514,
                'email' => 'hajaraswad333@gmail.com',
                'hp' => '085608684206',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-07 02:58:26',
                'updated_at' => '2025-05-24 15:45:25',
            ],
            [
                'id' => 41,
                'prodi_id' => 6,
                'kode' => '80140',
                'nidn' => '2130077601',
                'nama' => 'HELMI AL FAROBI',
                'gelar_depan' => null,
                'gelar_belakang' => null,
                'jk_id' => 8,
                'tempat_lahir' => 'KABUPATEN SIDOARJO',
                'tanggal_lahir' => '1976-07-30',
                'alamat' => 'PASURUAN',
                'kota_id' => 3575,
                'email' => 'llllk@gmail.com',
                'hp' => '0898989898',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 470,
                'user_id' => 8,
                'created_at' => '2021-01-07 03:03:59',
                'updated_at' => '2025-01-23 10:50:49',
            ],
            [
                'id' => 42,
                'prodi_id' => 6,
                'kode' => '80163',
                'nidn' => '2116067701',
                'nama' => 'MUHAMMAD ZUHDI',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.HI',
                'jk_id' => 8,
                'tempat_lahir' => 'KOTA PASURUAN',
                'tanggal_lahir' => '1977-06-16',
                'alamat' => 'Pasuruan',
                'kota_id' => 3514,
                'email' => 'mzsz7887@gmail.com',
                'hp' => '081937074144',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 7,
                'created_at' => '2021-01-07 03:11:02',
                'updated_at' => '2025-01-29 08:55:35',
            ],
            [
                'id' => 43,
                'prodi_id' => 8,
                'kode' => '80111',
                'nidn' => '2101027001',
                'nama' => 'Dr. S AHMAD AL HAMID',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Pd.I',
                'jk_id' => 8,
                'tempat_lahir' => 'KABUPATEN MALANG',
                'tanggal_lahir' => '1970-02-01',
                'alamat' => 'MALANG',
                'kota_id' => 3507,
                'email' => 'albinhamid@alkhoirot.com',
                'hp' => '085815167701',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-07 03:13:27',
                'updated_at' => '2025-07-15 08:15:32',
            ],
            [
                'id' => 44,
                'prodi_id' => 11,
                'kode' => '80159',
                'nidn' => '2127029001',
                'nama' => 'SYAMFA AGNY ANGGARA',
                'gelar_depan' => 'Dr.',
                'gelar_belakang' => 'M.Pd I',
                'jk_id' => 8,
                'tempat_lahir' => 'KOTA MALANG',
                'tanggal_lahir' => '1990-02-27',
                'alamat' => 'Jl. Kol. Sugiono gang 3b no.151',
                'kota_id' => 3573,
                'email' => 'agnyanggara.aa@gmail.com',
                'hp' => '0895331112366',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-07 03:15:39',
                'updated_at' => '2025-01-29 08:55:35',
            ],
            [
                'id' => 45,
                'prodi_id' => 10,
                'kode' => '80165',
                'nidn' => '2108078801',
                'nama' => 'AHMAD MUSTOFA',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Pd.I',
                'jk_id' => 8,
                'tempat_lahir' => 'KOTA SURABAYA',
                'tanggal_lahir' => '1988-07-08',
                'alamat' => 'SURABAYA',
                'kota_id' => 3578,
                'email' => 'ibnulhyn@gmail.com',
                'hp' => '081703359977',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-07 03:20:45',
                'updated_at' => '2025-05-24 13:40:14',
            ],
            [
                'id' => 46,
                'prodi_id' => 6,
                'kode' => '80169',
                'nidn' => '2127048101',
                'nama' => 'ARIF RAHMAN',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.HI',
                'jk_id' => 8,
                'tempat_lahir' => 'KABUPATEN PASURUAN',
                'tanggal_lahir' => '1983-04-27',
                'alamat' => 'PASURUAN',
                'kota_id' => 3514,
                'email' => 'rahmanalfalaharif@gmail.com',
                'hp' => '085236263334',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-07 03:23:28',
                'updated_at' => '2025-09-03 13:29:38',
            ],
            [
                'id' => 47,
                'prodi_id' => 7,
                'kode' => '80208',
                'nidn' => '2129048502',
                'nama' => 'HUSAIRI',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Pd.I',
                'jk_id' => 8,
                'tempat_lahir' => 'KABUPATEN BANGKALAN',
                'tanggal_lahir' => '1985-04-29',
                'alamat' => 'BOJONEGORO',
                'kota_id' => 3522,
                'email' => 'zairvtc@gmail.com',
                'hp' => '085755004977',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-07 06:45:31',
                'updated_at' => '2025-01-29 09:02:15',
            ],
            [
                'id' => 48,
                'prodi_id' => 7,
                'kode' => '80214',
                'nidn' => '2110088901',
                'nama' => 'MOCHAMMAD SIROJUL MUNIR',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Pd',
                'jk_id' => 8,
                'tempat_lahir' => 'KABUPATEN PASURUAN',
                'tanggal_lahir' => '1989-08-10',
                'alamat' => 'PASURUAN',
                'kota_id' => 3514,
                'email' => 'msirojulm@gmail.com',
                'hp' => '0895628067120',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-07 06:47:19',
                'updated_at' => '2025-01-29 08:55:35',
            ],
            [
                'id' => 49,
                'prodi_id' => 7,
                'kode' => '80064',
                'nidn' => '2102036701',
                'nama' => 'SAHRI',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.HI',
                'jk_id' => 8,
                'tempat_lahir' => 'KABUPATEN SAMBAS',
                'tanggal_lahir' => '1967-03-02',
                'alamat' => 'PASURUAN',
                'kota_id' => 3514,
                'email' => 'syahrisumuddin@gmail.com',
                'hp' => '081333192737',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-07 06:53:45',
                'updated_at' => '2025-01-29 08:55:35',
            ],
            [
                'id' => 50,
                'prodi_id' => 8,
                'kode' => '80225',
                'nidn' => '2123038802',
                'nama' => 'ABDULLAH ZAINI',
                'gelar_depan' => null,
                'gelar_belakang' => null,
                'jk_id' => 8,
                'tempat_lahir' => 'KABUPATEN PASURUAN',
                'tanggal_lahir' => '1988-03-23',
                'alamat' => 'PASURUAN',
                'kota_id' => 3514,
                'email' => 'zenzaini57@gmail.com',
                'hp' => '082231285523',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-07 06:58:35',
                'updated_at' => '2025-01-23 10:50:49',
            ],
            [
                'id' => 51,
                'prodi_id' => 8,
                'kode' => '80069',
                'nidn' => '2129127401',
                'nama' => 'ACHMAD DJUAINI',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Pd',
                'jk_id' => 8,
                'tempat_lahir' => 'KABUPATEN PASURUAN',
                'tanggal_lahir' => '1974-12-29',
                'alamat' => 'Malang',
                'kota_id' => 3507,
                'email' => 'juainiahmad14@gmail.com',
                'hp' => '081944996357',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-09 03:37:13',
                'updated_at' => '2025-01-30 06:51:35',
            ],
            [
                'id' => 52,
                'prodi_id' => 13,
                'kode' => '80005',
                'nidn' => '2115086801',
                'nama' => 'AKHMAD FAUZI HAMZAH',
                'gelar_depan' => 'Dr',
                'gelar_belakang' => 'M.Pd.I',
                'jk_id' => 8,
                'tempat_lahir' => 'KABUPATEN SUMENEP',
                'tanggal_lahir' => '1968-08-15',
                'alamat' => 'Jl Raya Raci Pondok 51 Rt 04 Rw 03 Kel Raci Kec Bangil Kab pasuruan',
                'kota_id' => 3514,
                'email' => 'af23@gmail.com',
                'hp' => '081937719391',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-09 03:46:50',
                'updated_at' => '2025-07-28 11:59:48',
            ],
            [
                'id' => 53,
                'prodi_id' => 8,
                'kode' => '80171',
                'nidn' => '2111018703',
                'nama' => 'ERNAKA HERI PUTRA SUHARYANTO',
                'gelar_depan' => 'Dr.',
                'gelar_belakang' => null,
                'jk_id' => 8,
                'tempat_lahir' => 'KABUPATEN JEMBER',
                'tanggal_lahir' => '1987-01-11',
                'alamat' => 'Ds Kepel Rt 05 Rw 25 Kel Ampel Kec Wuluhan Kab Jember',
                'kota_id' => 3509,
                'email' => 'er@yahoo.com',
                'hp' => '081234567891',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 470,
                'user_id' => 8,
                'created_at' => '2021-01-09 03:51:53',
                'updated_at' => '2025-01-30 06:51:35',
            ],
            [
                'id' => 54,
                'prodi_id' => 9,
                'kode' => '80240',
                'nidn' => '2115068705',
                'nama' => 'LAILY ZUNAIDA',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Pd',
                'jk_id' => 9,
                'tempat_lahir' => 'KABUPATEN PASURUAN',
                'tanggal_lahir' => '1987-07-15',
                'alamat' => 'Perum Pessona Wirolegi Rt 04 Rw 05 Kel Wirolegi Kec  Sumbersari Kab jember',
                'kota_id' => 3509,
                'email' => 'l.zunaida15@gmail.com',
                'hp' => '087794166797',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-09 03:56:27',
                'updated_at' => '2025-01-30 06:51:35',
            ],
            [
                'id' => 55,
                'prodi_id' => 8,
                'kode' => '80164',
                'nidn' => '2115098602',
                'nama' => 'MUKARROMAH',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Pd.I',
                'jk_id' => 9,
                'tempat_lahir' => 'KABUPATEN SIDOARJO',
                'tanggal_lahir' => '1986-09-15',
                'alamat' => 'Dsn Genengan Rt 01 rw 02 Kel Glagahsari Kec Sukorejo Kab Pasuruan',
                'kota_id' => 3514,
                'email' => 'mukarromah2378@gmail.com',
                'hp' => '085655531195',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-09 04:00:46',
                'updated_at' => '2025-01-29 08:55:35',
            ],
            [
                'id' => 56,
                'prodi_id' => 8,
                'kode' => '80131',
                'nidn' => '2103088301',
                'nama' => 'AKHMAD SAHRANDI',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Pd.I',
                'jk_id' => 8,
                'tempat_lahir' => 'KABUPATEN SUMENEP',
                'tanggal_lahir' => '1983-08-03',
                'alamat' => 'PASURUAN',
                'kota_id' => 3514,
                'email' => 'sahrandi@gmail.com',
                'hp' => '081937128923',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-09 04:03:24',
                'updated_at' => '2025-01-29 09:02:15',
            ],
            [
                'id' => 57,
                'prodi_id' => 9,
                'kode' => '80231',
                'nidn' => '2101018710',
                'nama' => 'NOVI ARIYANTI',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Pd',
                'jk_id' => 9,
                'tempat_lahir' => 'KABUPATEN PASURUAN',
                'tanggal_lahir' => '1987-01-01',
                'alamat' => 'Dsn Kandangsari Rt 02 Rw 04 Kel Capang Kec Purwodadi Kab Pasuruan',
                'kota_id' => 3514,
                'email' => 'noviariyanti2017@gmail.com',
                'hp' => '085816116941',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-09 04:08:48',
                'updated_at' => '2025-01-29 08:55:35',
            ],
            [
                'id' => 58,
                'prodi_id' => 9,
                'kode' => '80174',
                'nidn' => '2130048403',
                'nama' => 'SURYANTO',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Pd.I',
                'jk_id' => 8,
                'tempat_lahir' => 'KABUPATEN KETAPANG',
                'tanggal_lahir' => '1984-10-30',
                'alamat' => 'Dsn Sukorejo Kel Sumberejo Kec Banyuputih Kab Situbondo',
                'kota_id' => 3512,
                'email' => 'sur01@yahoo.com',
                'hp' => '081234098123',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 470,
                'user_id' => 8,
                'created_at' => '2021-01-09 04:13:36',
                'updated_at' => '2025-01-29 08:55:35',
            ],
            [
                'id' => 59,
                'prodi_id' => 9,
                'kode' => '80152',
                'nidn' => '2104048405',
                'nama' => 'UNUN ZUMAIROH ASRHIMSYAH',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Pd',
                'jk_id' => 9,
                'tempat_lahir' => 'KABUPATEN MALANG',
                'tanggal_lahir' => '1984-04-04',
                'alamat' => 'Dsn Pitrang RT 19 RW 05 Kec Kalipare Kab Malang',
                'kota_id' => 3507,
                'email' => 'ununzumairoh@gmail.com',
                'hp' => '085608543222',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-09 04:19:28',
                'updated_at' => '2025-01-29 08:55:35',
            ],
            [
                'id' => 60,
                'prodi_id' => 10,
                'kode' => '80079',
                'nidn' => '2127107001',
                'nama' => 'ABDURRAHMAN AHMAD AGIL',
                'gelar_depan' => 'Dr.',
                'gelar_belakang' => 'M.HI',
                'jk_id' => 8,
                'tempat_lahir' => 'KOTA SURABAYA',
                'tanggal_lahir' => '1970-10-27',
                'alamat' => 'Jl Ketapang Besar Rt 02 Rw 01 Kel Ampel Kec Semampir Surabaya',
                'kota_id' => 3578,
                'email' => 'abd123agil@gmail.com',
                'hp' => '087856826747',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-09 04:31:32',
                'updated_at' => '2025-09-28 07:40:18',
            ],
            [
                'id' => 61,
                'prodi_id' => 5,
                'kode' => '80218',
                'nidn' => '2104029002',
                'nama' => 'AGUNG IS HARDIYANA FEBRY',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Pd',
                'jk_id' => 8,
                'tempat_lahir' => 'KABUPATEN JEMBER',
                'tanggal_lahir' => '1990-02-04',
                'alamat' => 'Jl Darmawangsan IV/6 Rt 01 Rw 02 Kel Kaliwining Kec Rambipuji Kab Jember',
                'kota_id' => 3509,
                'email' => 'agung.febry0402@gmail.com',
                'hp' => '085850193880',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-09 04:37:52',
                'updated_at' => '2025-01-29 08:55:35',
            ],
            [
                'id' => 62,
                'prodi_id' => 10,
                'kode' => '80162',
                'nidn' => '2123038501',
                'nama' => 'ALVIA PUTRI PRIMA SARI',
                'gelar_depan' => 'Dr',
                'gelar_belakang' => 'M.Pd.I',
                'jk_id' => 9,
                'tempat_lahir' => 'KOTA MALANG',
                'tanggal_lahir' => '1985-03-23',
                'alamat' => 'Puri Cempaka Putih Kel Arjowinangun Kec Kedungkandang Kota Malang',
                'kota_id' => 3573,
                'email' => 'alviap23@gmail.com',
                'hp' => '081393947478',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 5907,
                'created_at' => '2021-01-09 04:42:48',
                'updated_at' => '2025-01-30 06:51:35',
            ],
            [
                'id' => 63,
                'prodi_id' => 10,
                'kode' => '80235',
                'nidn' => '2127058802',
                'nama' => 'ARDIANTI',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Pd',
                'jk_id' => 9,
                'tempat_lahir' => 'KABUPATEN PASURUAN',
                'tanggal_lahir' => '1988-05-27',
                'alamat' => 'Jl Kauman No 243 Rt 08 Rw 02 Kel Kauman Kec Bangil Kab Pasuruan',
                'kota_id' => 3514,
                'email' => 'dian11ardianti@gmail.com',
                'hp' => '082145345128',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-09 04:48:13',
                'updated_at' => '2025-01-30 06:51:35',
            ],
            [
                'id' => 64,
                'prodi_id' => 10,
                'kode' => '80119',
                'nidn' => '2113039001',
                'nama' => 'BAHRUL ULUM',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Pd.I',
                'jk_id' => 8,
                'tempat_lahir' => 'KABUPATEN BANGKALAN',
                'tanggal_lahir' => '1990-03-13',
                'alamat' => 'Kmp Nipa Rt 02 Rw 02 Kel Paeng Kec Modung Kab Bangkalan',
                'kota_id' => 3526,
                'email' => 'tahfid.oke@gmail.com',
                'hp' => '082231362337',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-09 04:52:32',
                'updated_at' => '2025-01-30 06:51:35',
            ],
            [
                'id' => 65,
                'prodi_id' => 8,
                'kode' => '80242',
                'nidn' => '2101037906',
                'nama' => 'BULHAYAT',
                'gelar_depan' => null,
                'gelar_belakang' => null,
                'jk_id' => 8,
                'tempat_lahir' => 'KABUPATEN SUMENEP',
                'tanggal_lahir' => '1979-03-01',
                'alamat' => 'PASURUAN',
                'kota_id' => 3514,
                'email' => 'bulhayatazmi@gmail.com',
                'hp' => '0895327409742',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-09 06:29:11',
                'updated_at' => '2025-05-24 13:46:55',
            ],
            [
                'id' => 66,
                'prodi_id' => 12,
                'kode' => '80046',
                'nidn' => '2108017701',
                'nama' => 'IMADUDDIN',
                'gelar_depan' => 'Dr',
                'gelar_belakang' => 'M.Pd.I',
                'jk_id' => 8,
                'tempat_lahir' => 'KABUPATEN SANGGAU',
                'tanggal_lahir' => '1977-01-08',
                'alamat' => 'PASURUAN',
                'kota_id' => 3514,
                'email' => 'imaduddinsabran77@gmail.com',
                'hp' => '081936810951',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-09 06:33:55',
                'updated_at' => '2025-01-30 06:51:35',
            ],
            [
                'id' => 67,
                'prodi_id' => 8,
                'kode' => '80092',
                'nidn' => '2125067802',
                'nama' => 'LUTFI RACHMAN',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Pd.I',
                'jk_id' => 8,
                'tempat_lahir' => 'KOTA SURABAYA',
                'tanggal_lahir' => '1978-06-25',
                'alamat' => 'PASURUAN',
                'kota_id' => 3578,
                'email' => 'lutfirachman09@gmail.com',
                'hp' => '081938156561',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-09 06:37:02',
                'updated_at' => '2025-05-09 18:22:09',
            ],
            [
                'id' => 68,
                'prodi_id' => 4,
                'kode' => '80237',
                'nidn' => '0724088801',
                'nama' => 'FIFIN NAILI RIZKIYAH',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Pd',
                'jk_id' => 9,
                'tempat_lahir' => 'KABUPATEN PROBOLINGGO',
                'tanggal_lahir' => '1988-08-24',
                'alamat' => 'Dsn Krajan No 192 Rt 06 Rw 03 Kel Dungun Kec Tongas Kab Probolinggo',
                'kota_id' => 3513,
                'email' => 'phiefin@gmail.com',
                'hp' => '0895398355029',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 10771,
                'created_at' => '2021-01-09 06:38:33',
                'updated_at' => '2025-07-28 10:26:51',
            ],
            [
                'id' => 69,
                'prodi_id' => 11,
                'kode' => '80047',
                'nidn' => '2031127410',
                'nama' => 'MASNUN',
                'gelar_depan' => 'Dr.',
                'gelar_belakang' => 'M.Pd',
                'jk_id' => 8,
                'tempat_lahir' => 'KABUPATEN LOMBOK TIMUR',
                'tanggal_lahir' => '1974-12-31',
                'alamat' => 'Jl. Masjid al-Karomah Rt. 08 Rw. 05 Ngering Kelurahan Legok Kecamatan Gempol',
                'kota_id' => 3514,
                'email' => 'masnun513@gmail.com',
                'hp' => '08179335526',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-09 06:40:44',
                'updated_at' => '2025-09-23 18:33:31',
            ],
            [
                'id' => 70,
                'prodi_id' => 10,
                'kode' => '80125',
                'nidn' => '2127027701',
                'nama' => 'MOH. TOHIRI HABIB',
                'gelar_depan' => 'Dr.',
                'gelar_belakang' => 'M.Pd',
                'jk_id' => 8,
                'tempat_lahir' => 'KABUPATEN LAMONGAN',
                'tanggal_lahir' => '1977-02-27',
                'alamat' => 'Jl S Kalijogo No 29 Rt 03 Rw 12 Kec Babat Kab Babat Lamongan',
                'kota_id' => 3524,
                'email' => 'tohirihb@gmail.com',
                'hp' => '081357728975',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 5913,
                'created_at' => '2021-01-09 06:44:40',
                'updated_at' => '2025-01-30 06:51:35',
            ],
            [
                'id' => 71,
                'prodi_id' => 8,
                'kode' => '80207',
                'nidn' => '2101017702',
                'nama' => 'SAPARWADI',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Pd',
                'jk_id' => 8,
                'tempat_lahir' => 'KABUPATEN LOMBOK TIMUR',
                'tanggal_lahir' => '1977-01-01',
                'alamat' => 'PASURUAN',
                'kota_id' => 3514,
                'email' => 'safarwadiabu940@gmail.com',
                'hp' => '081803255996',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-09 06:45:06',
                'updated_at' => '2025-01-29 08:55:35',
            ],
            [
                'id' => 72,
                'prodi_id' => 10,
                'kode' => '80146',
                'nidn' => '2105078802',
                'nama' => 'YUSUF ARISANDI',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Pd.I',
                'jk_id' => 8,
                'tempat_lahir' => 'KABUPATEN LUMAJANG',
                'tanggal_lahir' => '1988-07-05',
                'alamat' => 'JALAN GAJAH MADA NO. 84, RT.15/RW.05, DUKUH NGINGAS, WARU',
                'kota_id' => 3515,
                'email' => 'yusufarisandi@uiidalwa.ac.id',
                'hp' => '089520031514',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-09 06:47:47',
                'updated_at' => '2025-06-01 14:26:15',
            ],
            [
                'id' => 73,
                'prodi_id' => 10,
                'kode' => '80161',
                'nidn' => '2115048502',
                'nama' => 'MUSTAHAR ALI WARDANA',
                'gelar_depan' => 'Dr.',
                'gelar_belakang' => 'M.Pd',
                'jk_id' => 8,
                'tempat_lahir' => 'KABUPATEN BANYUWANGI',
                'tanggal_lahir' => '1985-04-15',
                'alamat' => 'Jl Bandung No 07 Rt 04 Rw 02 Kel Penanggungan Kec Klojen Kota Malang',
                'kota_id' => 3573,
                'email' => 'aliut85@gmail.com',
                'hp' => '08563216431',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-09 06:48:56',
                'updated_at' => '2025-01-29 08:55:35',
            ],
            [
                'id' => 74,
                'prodi_id' => 13,
                'kode' => '80999',
                'nidn' => '2101015601',
                'nama' => 'ALI MASCHAN MOESA',
                'gelar_depan' => 'Dr.',
                'gelar_belakang' => 'M.S.I',
                'jk_id' => 8,
                'tempat_lahir' => 'KABUPATEN TULUNGAGUNG',
                'tanggal_lahir' => '1956-01-01',
                'alamat' => 'TULUNGAGUNG',
                'kota_id' => 3504,
                'email' => 'alimaschan0101@gmail.com',
                'hp' => '0811379159',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 470,
                'user_id' => 8,
                'created_at' => '2021-01-11 03:13:42',
                'updated_at' => '2025-01-23 10:50:49',
            ],
            [
                'id' => 75,
                'prodi_id' => 12,
                'kode' => '80228',
                'nidn' => '2127088102',
                'nama' => 'ENDAH WINARTI',
                'gelar_depan' => 'Dr',
                'gelar_belakang' => 'M.Pd',
                'jk_id' => 9,
                'tempat_lahir' => 'KOTA MALANG',
                'tanggal_lahir' => '1981-08-27',
                'alamat' => 'MALANG',
                'kota_id' => 3573,
                'email' => 'endahwinarti002@gmail.com',
                'hp' => '08563431170',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-11 03:16:04',
                'updated_at' => '2025-01-30 06:51:35',
            ],
            [
                'id' => 76,
                'prodi_id' => 12,
                'kode' => '80243',
                'nidn' => '0710127905',
                'nama' => 'MUHAMMAD UBAIDILLAH',
                'gelar_depan' => 'Dr.',
                'gelar_belakang' => 'M.Pd,',
                'jk_id' => 8,
                'tempat_lahir' => 'KABUPATEN PROBOLINGGO',
                'tanggal_lahir' => '1979-12-10',
                'alamat' => 'BANGKALAN',
                'kota_id' => 3526,
                'email' => 'aubaidillahmuhammad01@gmail.com',
                'hp' => '081937719391',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-11 03:31:26',
                'updated_at' => '2025-01-29 08:55:35',
            ],
            [
                'id' => 77,
                'prodi_id' => 12,
                'kode' => '80230',
                'nidn' => '2127018503',
                'nama' => 'SODIKIN',
                'gelar_depan' => 'Dr.',
                'gelar_belakang' => 'M.Pd I',
                'jk_id' => 8,
                'tempat_lahir' => 'KABUPATEN PASURUAN',
                'tanggal_lahir' => '1985-01-27',
                'alamat' => 'PASURUAN',
                'kota_id' => 3514,
                'email' => 'aremaniasolikin52@gmail.com',
                'hp' => '087828522272',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 10770,
                'created_at' => '2021-01-11 03:37:29',
                'updated_at' => '2025-08-04 09:44:30',
            ],
            [
                'id' => 78,
                'prodi_id' => 13,
                'kode' => '80004',
                'nidn' => '2113127102',
                'nama' => 'ZAINAL ABIDIN',
                'gelar_depan' => 'Dr.',
                'gelar_belakang' => 'M.Pd',
                'jk_id' => 8,
                'tempat_lahir' => 'KOTA MALANG',
                'tanggal_lahir' => '1971-12-13',
                'alamat' => 'MALANG',
                'kota_id' => 3573,
                'email' => 'zainal.almadaniyah@gmail.com',
                'hp' => '085755004977',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 10770,
                'created_at' => '2021-01-11 03:41:11',
                'updated_at' => '2025-08-08 08:06:46',
            ],
            [
                'id' => 79,
                'prodi_id' => 8,
                'kode' => '80205',
                'nidn' => '2107078501',
                'nama' => 'ASEP RAHMATULLAH',
                'gelar_depan' => 'Dr.',
                'gelar_belakang' => 'M.Pd.I',
                'jk_id' => 8,
                'tempat_lahir' => 'KABUPATEN SERANG',
                'tanggal_lahir' => '1985-07-07',
                'alamat' => 'SERANG',
                'kota_id' => 3604,
                'email' => 'asepofficial85@gmail.com',
                'hp' => '085749300234',
                'dosen_status_id' => 23,
                'status_dosen_tetap_id' => 469,
                'user_id' => 8,
                'created_at' => '2021-01-11 03:43:58',
                'updated_at' => '2025-10-12 07:03:49',
            ],
        ]);
    }
}
